apiVersion: v1
kind: ServiceAccount
metadata:
  name: netperf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netperf
  labels:
    app: netperf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netperf
  template:
    metadata:
      labels:
        app: netperf
    spec:
      containers:
      - name: netperf
        image: weny017/netperf
